LOG_LEVEL = "INFO"

GOOGLE_DRIVE_POLL_PAGE_SIZE = 100

QDRANT_KNOWLEDGE_BASE_COLLECTION = "knowledge_base"
QDRANT_QUESTION_BANK_COLLECTION = "question_bank"
QDRANT_GENERATED_QUESTIONS_COLLECTION = "generated_questions"
QDRANT_PIPELINE_STATE_COLLECTION = "pipeline_state"
QDRANT_VECTOR_SIZE = 768
QDRANT_DISTANCE = "Cosine"
QDRANT_UPSERT_BATCH_SIZE = 64

EMBEDDING_MODEL_NAME = "BAAI/bge-base-en-v1.5"
EMBEDDING_DEVICE = "cpu"
EMBEDDING_BATCH_SIZE = 16
EMBEDDING_MAX_LENGTH = 8192
EMBEDDING_USE_FP16 = False

CHUNK_SIZE = 800
CHUNK_OVERLAP = 120
MIN_CHUNK_SIZE = 50

SCHEDULER_INTERVAL_SECONDS = 180
SCHEDULER_MAX_CONCURRENT_JOBS = 3
SCHEDULER_ENABLED = True

WORKER_MAX_RETRIES = 3
WORKER_RETRY_BACKOFF_SECONDS = 5

OCR_LANGUAGE = "en"
OCR_USE_GPU = False
SCANNED_PDF_TEXT_THRESHOLD = 50

FAILED_QUEUE_PATH = "/app/data/failed_queue.json"

APP_NAME = "ai-ingestion-pipeline"
APP_VERSION = "1.0.0"